[build]
  publish = "out"  # Diretório de saída
  command = "npm run build"  # Comando de build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
