[build]
  publish = "out"  # Certifique-se de que este é o diretório correto onde o Next.js exporta os arquivos estáticos.
  command = "npm run build && npm run export"  # Comando para construir e exportar o projeto.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
